blank_issues_enabled: true
contact_links:
  - name: "Πρόταση μέσω ιστοσελίδας LibreHub"
    url: "https://librehub.netlify.app/suggest"
    about: "Αν δεν διαθέτετε λογαριασμό GitHub, μπορείτε να υποβάλετε την πρότασή σας μέσω της φόρμας στην ιστοσελίδα."
